In [1]:
import numpy as np 

In [38]:
history_len = 5
# policy_obs_mirror_indices = [0, 1, 2,\
#                              3, 4, 5,\
#                              6, 7, 8,\
#                              10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20, 19, 22, 21, 24, 23, 26, 25, 28, 27, 30, 29, 32, 31, 34, 33, \
#                              36, 35, 38, 37, 40, 39, 42, 41, 44, 43, 46, 45, 48, 47, 50, 49, 52, 51, 54, 53, 56, 55, 58, 57, 60, 59, \
#                              62, 61, 64, 63, 66, 65, 68, 67, 70, 69, 72, 71, 74, 73, 76, 75, 78, 77, 80, 79, 82, 81, 84, 83, 86, 85]

# policy_obs_mirror_signs = [-1, 1, -1,\
#                            1, -1, 1,\
#                            1, -1, -1,\
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]

# critic_obs_mirror_indices = [0, 1, 2,\
#                              3, 4, 5,\
#                              6, 7, 8,\
#                              10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20, 19, 22, 21, 24, 23, 26, 25, 28, 27, 30, 29, 32, 31, 34, 33, \
#                              36, 35, 38, 37, 40, 39, 42, 41, 44, 43, 46, 45, 48, 47, 50, 49, 52, 51, 54, 53, 56, 55, 58, 57, 60, 59, \
#                              62, 61, 64, 63, 66, 65, 68, 67, 70, 69, 72, 71, 74, 73, 76, 75, 78, 77, 80, 79, 82, 81, 84, 83, 86, 85, \
#                              87, 88, 89, \
#                              91, 90, 93, 92, 95, 94, 97, 96, 99, 98, 101, 100, 103, 102, 105, 104, 107, 106, 109, 108, 111, 110, 113, 112, 115, 114, \
#                              117, 116, 119, 118, 121, 120, 123, 122, 125, 124, 127, 126, 129, 128, 131, 130, 133, 132, 135, 134, 137, 136, 139, 138, 141, 140, \
#                              145, 146, 147, 142, 143, 144, \
#                              151, 152, 153, 148, 149, 150, \
#                              154, \
#                              158, 159, 160, 155, 156, 157, \
#                              161, 162, 163, \
#                              164, \
#                              165, 166, 167, \
#                              168, 169, 170, \
#                              172, 171, \
#                              174, 173]
# critic_obs_mirror_signs = [-1, 1, -1,\
#                            1, -1, 1,\
#                            1, -1, -1,\
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            1, -1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, \
#                            1, -1, 1, 1, -1, 1, \
#                            1, -1, 1, 1, -1, 1, \
#                            1, \
#                            1, 1, 1, 1, 1, 1, \
#                            1, -1, 1, \
#                            1, \
#                            1, -1, 1, \
#                            -1, 1, -1, \
#                            1, 1, \
#                            1, 1]

singleObs = {
            "base_ang_vel":[[0, 1, 2],[-1,1,-1]],
            "gravity":[[0,1,2],[1,-1,1]],
            "cmd":[[0,1,2],[1, -1, -1]],
            "joint_pos":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "joint_vel":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "action":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]]
        }
singleCriticObs = {
            "base_ang_vel":[[0, 1, 2],[-1,1,-1]],
            "gravity":[[0,1,2],[1,-1,1]],
            "cmd":[[0,1,2],[1, -1, -1]],
            "joint_pos":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "joint_vel":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "action":[[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "base_lin_vel": [[0, 1, 2],[1, -1, 1]],
            "joint_torques": [[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "joint_accs": [[1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11, 10,
                            13, 12, 15, 14, 17,16, 19, 18, 21, 20, 23, 22, 25, 24],
                        [-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1]],
            "feet_lin_vel": [[3, 4, 5, 0, 1, 2],[1, -1, 1, 1, -1, 1]],
            "feet_contact_force": [[3, 4, 5, 0, 1, 2],[1, -1, 1, 1, -1, 1]],
            "base_mass_rel": [[0,],[1,]],
            "rigid_body_material": [[3, 4, 5, 0, 1, 2],[1, 1, 1, 1, 1, 1]],
            "base_com": [[0,1,2],[1,-1,1]],
            "action_delay": [[0,],[1,]],
            "push_force": [[0,1,2],[1,-1,1]],
            "push_torque": [[0, 1, 2],[-1,1,-1]],
            "feet_heights": [[1,0],[1,1]],
            "feet_air_times": [[1,0],[1,1]],
}
idx = 0
policy_obs_mirror_indices = []
policy_obs_mirror_signs = []
for k in singleObs:
    n = len(singleObs[k][0])
    for i in range(history_len):
        start_idx = idx 
        end_idx = idx + n
        policy_obs_mirror_indices.extend([i+start_idx for i in singleObs[k][0]])
        policy_obs_mirror_signs.extend(singleObs[k][1])
        idx += n

policy_obs_mirror_indices = np.array(policy_obs_mirror_indices).reshape(-1)
policy_obs_mirror_signs = np.array(policy_obs_mirror_signs).reshape(-1)
# mirror critic obs
critic_obs_mirror_indices = []
critic_obs_mirror_signs = []
idx = 0
for k in singleCriticObs:
    n = len(singleCriticObs[k][0])
    for i in range(history_len):
        start_idx = idx 
        end_idx = idx + n
        critic_obs_mirror_indices.extend([i+start_idx for i in singleCriticObs[k][0]])
        critic_obs_mirror_signs.extend(singleCriticObs[k][1])
        idx += n
critic_obs_mirror_indices = np.array(critic_obs_mirror_indices).reshape(-1)
critic_obs_mirror_signs = np.array(critic_obs_mirror_signs).reshape(-1)

In [35]:
# policy_obs_mirror_signs[:45].reshape(-1,history_len*3)
mirror_joint_signs = policy_obs_mirror_signs[45:history_len*26]

In [19]:
mirror_joint_indices = np.array(policy_obs_mirror_indices)[45:history_len*26]

In [37]:

gt = np.array([-1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1])
mirror_joint_signs[:26] - gt

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [41]:
critic_obs_mirror_indices[:87*history_len] - policy_obs_mirror_indices

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [44]:
critic_obs_mirror_signs[:87*history_len] - policy_obs_mirror_signs

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [3]:
OBSTERMLAB2GYM = {
            "base_ang_vel":[0,1,2],
            "gravity":[0,1,2],
            "cmd":[0,1,2,3],
            "cmd_vel":[0,1,2],
            "hugwbc_cmd":[0],
            "joint_pos":[0, 4, 8, 12, 16, 20, 1, 5, 9, 13, 17, 21, 2, 6, 10, 14, 18, 22, 24, 3, 7, 11, 15, 19, 23, 25],
            "joint_vel":[0, 4, 8, 12, 16, 20, 1, 5, 9, 13, 17, 21, 2, 6, 10, 14, 18, 22, 24, 3, 7, 11, 15, 19, 23, 25],
            "action":[0, 4, 8, 12, 16, 20, 1, 5, 9, 13, 17, 21, 2, 6, 10, 14, 18, 22, 24, 3, 7, 11, 15, 19, 23, 25]
        }
OBSTERMGYM2LAB = {
            "base_ang_vel":[0,1,2],
            "gravity":[0,1,2],
            "cmd":[0,1,2,3],
            "cmd_vel":[0,1,2],
            "hugwbc_cmd":[0],
            "joint_pos":[0, 6, 12, 19, 1, 7, 13, 20, 2, 8, 14, 21, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25],
            "joint_vel":[0, 6, 12, 19, 1, 7, 13, 20, 2, 8, 14, 21, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25],
            "action":[0, 6, 12, 19, 1, 7, 13, 20, 2, 8, 14, 21, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25]
        }

def generate_lab_obs_indices(obs_keys:dict,history_len:int)->np.array:
    """
    将gym的风格的观测转换为lab的索引 obs[indices]->[obs_1[0:h],obs_2[0:h],...]
    """
    policy_obs_idx = 0 
    single_gym2lab_dict = {}
    single_gym2lab = np.array([])
    # 先构建(history, N)的矩阵，然后将其改为列存储
    for k in obs_keys:
        term_gym2lab = np.array(OBSTERMGYM2LAB[k])
        n = term_gym2lab.shape[0]
        single_gym2lab_dict[k] = [policy_obs_idx, policy_obs_idx+n]
        single_gym2lab = np.concatenate((single_gym2lab, term_gym2lab+policy_obs_idx), axis=-1)
        policy_obs_idx += n
    gym2lab_mat = [single_gym2lab + i * single_gym2lab.shape[0] for i in range(history_len)]
    gym2lab_mat = np.array(gym2lab_mat).reshape(history_len,-1)  # 此时每行是一个
    gym2lab = np.array([])

    for k in obs_keys:
        start_idx = single_gym2lab_dict[k][0]
        end_idx = single_gym2lab_dict[k][1]
        for i in range(history_len):
            obs_i = gym2lab_mat[i]
            gym2lab = np.concatenate((gym2lab, obs_i[start_idx:end_idx]))
    gym2lab = np.array(gym2lab).reshape(-1)
    return gym2lab


def generate_gym_obs_indices(obs_keys:dict,history_len:int)->np.array:
    """
    生成gym风格的观测索引 obs[indices]-> [obs_1,obs_2,...,obs_n]
    """
    single_lab2gym = np.array([])
    single_add_indices = np.array([])
    # 先构建(history, N)的矩阵，然后将其改为列存储
    skip_indices = 0
    for k in obs_keys:
        term_lab2gym = np.array(OBSTERMLAB2GYM[k])
        n = term_lab2gym.shape[0]  # 该观测项的维度
        single_lab2gym = np.concatenate((single_lab2gym, term_lab2gym+skip_indices), axis=-1)
        single_add_indices = np.concatenate((single_add_indices, np.array([n]*n)), axis=-1)
        skip_indices += n*history_len
    lab2gym = [single_lab2gym + single_add_indices*i for i in range(history_len)]
    lab2gym = np.array(lab2gym).reshape(-1)
    return lab2gym

In [ ]:
obsTerm = ["base_ang_vel", "gravity", "cmd"]
gym2lab = generate_lab_obs_indices(obsTerm, 5)
lab2gym = generate_gym_obs_indices(obsTerm, 5)

In [9]:
gym2lab[lab2gym.astype(np.int32)]==np.arange(0,50,1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])